RedditOnRails/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]

  resource :session, only: [:new, :create, :destroy]

  resources :subs do
    resources :posts, only: [:new, :create]
  end

  resources :posts, except: [:new, :create] do
    resources :comments, only: [:new]
  end

  resources :comments, only: [:create, :show]
end

RedditOnRails/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :title, presence: true

  belongs_to :author,
    foreign_key: :author_id,
    class_name: :User

  has_many :post_subs
  has_many :subs, through: :post_subs

  has_many :comments
end

RedditOnRails/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_author, only: [:edit]

  def new
    @post = Post.new
    render :new
  end

  def create
    post = Post.new(post_params)
    post.author_id = current_user.id

    if post.save
      redirect_to subs_url
    else
      flash[:errors] = post.errors.full_messages
      redirect_to new_sub_post_url
    end
  end

  def edit
    render :edit
  end

  def update
    post = Post.find(params[:id])

    if post.update(post_params)
      redirect_to post_url(post)
    else
      flash[:errors] = post.errors.full_messages
      redirect_to edit_post_url(post)
    end
  end

  def show
    @post = Post.find(params[:id])

    if @post
      render :show
    else
      redirect_to subs_url
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end

  def require_author
    @post = Post.find(params[:id])

    if @post.author_id != current_user.id
      flash[:errors] = ["You are not authorized to edit this post!"]
      redirect_to post_url(@post)
    end
  end
end

RedditOnRails/app/helpers/posts_helper.rb
module PostsHelper
end

RedditOnRails/app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<form class="" action="<%= post_url(@post) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="patch">

  <label>
    Title
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>

  <br>

  <label>
    URL
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label>

  <br>

  <label>
    Content
    <input type="text" name="post[content]" value="<%= @post.content %>">
  </label>

  <label>
    Which subs to post to?
    <input type="hidden" name="post[sub_ids][]" value="">

    <br>
    <% Sub.all.each do |sub| %>
      <input
        type="checkbox"
        name="post[sub_ids][]"
        value="<%= sub.id %>"
        <%= "checked" if @post.sub_ids.include?(sub.id) %>
      >
        <%= sub.title %>
      <br>
    <% end %>
  </label>

  <input type="submit" name="" value="Edit Post">
</form>

RedditOnRails/app/views/posts/new.html.erb
<h2>Create New Post</h2>

<form class="" action="<%= sub_posts_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>
    Title
    <input type="text" name="post[title]" value="">
  </label>

  <br>

  <label>
    URL
    <input type="text" name="post[url]" value="">
  </label>

  <br>

  <label>
    Content
    <input type="text" name="post[content]" value="">
  </label>

  <br>

  <label>
    Which subs to post to?
    <input type="hidden" name="post[sub_ids][]" value="">

    <br>
    <% Sub.all.each do |sub| %>
      <input
        type="checkbox"
        name="post[sub_ids][]"
        value="<%= sub.id %>"
      >
        <%= sub.title %>
      <br>
    <% end %>
  </label>

  <input type="submit" name="" value="Create New Post">
</form>

RedditOnRails/app/views/posts/show.html.erb
<h2><%= @post.title %></h2>

<ul>
  <li><strong>Created by: </strong><%= @post.author.username %></li>
  <br>
  <li><strong>URL: </strong><%= @post.url %></li>
  <br>
  <li><strong>Content: </strong><%= @post.content %></li>
</ul>

<h3>Comments</h3>

<ul>
  <% @post.comments.where(parent_comment_id: nil).each do |comment| %>
    <li>
      By: <%= comment.author.username %>
      <br>
      <%= comment.content %>
      <a href="<%= comment_url(comment) %>">Go to Comment</a>
    </li>
  <% end %>
</ul>

<a href="<%= edit_post_url(@post) %>">Edit Post</a>
<br>
<a href="<%= subs_url %>">Back to all Subs</a>
<br>
<a href="<%= new_post_comment_url(@post) %>">Add Top Level Comment</a>