RedditOnRails/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]

  resource :session, only: [:new, :create, :destroy]

  resources :subs do
    resources :posts, only: [:new, :create]
  end

  resources :posts, except: [:new, :create] do
    resources :comments, only: [:new]
  end

  resources :comments, only: [:create, :show]
end

RedditOnRails/app/views/layouts/_errors.html.erb
<% if flash[:errors] %>
  <ul>
    <% flash[:errors].each do |error| %>
      <li style="color: red"><%= error %></li>
    <% end %>
  </ul>
<% end %>

RedditOnRails/app/views/layouts/_top_page.html.erb
<% if logged_in? %>
  <p>Logged in as: <%= current_user.username %></p>

  <form class="" action="<%= session_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="delete">


    <input type="submit" name="" value="Log Out">
  </form>
<% else %>
  <a href="<%= new_user_url %>">Sign Up</a>
  <a href="<%= new_session_url %>">Sign In</a>
<% end %>

RedditOnRails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditOnRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/top_page' %>
    <%= render 'layouts/errors' %>

    <%= yield %>
  </body>
</html>