RedditOnRails/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]

  resource :session, only: [:new, :create, :destroy]

  resources :subs do
    resources :posts, only: [:new, :create]
  end

  resources :posts, except: [:new, :create] do
    resources :comments, only: [:new]
  end

  resources :comments, only: [:create, :show]
end

RedditOnRails/app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id                :bigint(8)        not null, primary key
#  content           :text             not null
#  author_id         :integer          not null
#  post_id           :integer          not null
#  parent_comment_id :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Comment < ApplicationRecord
  validates :content, presence: true

  belongs_to :author, {
    foreign_key: :author_id,
    class_name: 'User'
  }

  belongs_to :post

  belongs_to :parent_comment, {
    foreign_key: :parent_comment_id,
    class_name: 'Comment',
    optional: true
  }

  has_many :child_comments, {
    foreign_key: :parent_comment_id,
    class_name: 'Comment'
  }

  def has_parent?
    !!self.parent_comment_id
  end

end

RedditOnRails/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    render :new
  end

  def create
    comment = Comment.new(comment_params)
    comment.author_id = current_user.id

    if comment.save
      redirect_after_save(comment)
    else
      flash[:errors] = comment.errors.full_messages
      redirect_to new_post_comment_url(comment.post_id)
    end
  end

  def show
    @comment = Comment.find(params[:id])
    render :show
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :post_id, :parent_comment_id)
  end

  def redirect_after_save(comment)
    if comment.has_parent?
      redirect_to comment_url(comment.parent_comment_id)
    else
      redirect_to post_url(comment.post_id)
    end
  end
end

RedditOnRails/app/helpers/comments_helper.rb
module CommentsHelper
end

RedditOnRails/app/views/comments/new.html.erb
<h2>Create New Comment</h2>

<form class="" action="<%= comments_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="comment[post_id]" value="<%= params[:post_id] %>">

  <label>
    Content
    <input type="text" name="comment[content]" value="">
  </label>

  <input type="submit" name="" value="Post Comment">
</form>

RedditOnRails/app/views/comments/show.html.erb
<h4><%= @comment.content %></h4>

<ul>
  <% @comment.child_comments.each do |child_comment| %>
    <li><%= child_comment.content %></li>
  <% end %>
</ul>

<form class="" action="<%= comments_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="comment[post_id]" value="<%= @comment.post.id %>">
  <input type="hidden" name="comment[parent_comment_id]" value="<%= params[:id] %>">

  <label>
    Reply
    <input type="text" name="comment[content]" value="">
  </label>

  <input type="submit" name="" value="Reply">
</form>

<a href="<%= post_url(@comment.post_id) %>">Back to original post</a>