RedditOnRails/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]

  resource :session, only: [:new, :create, :destroy]

  resources :subs do
    resources :posts, only: [:new, :create]
  end

  resources :posts, except: [:new, :create] do
    resources :comments, only: [:new]
  end

  resources :comments, only: [:create, :show]
end

RedditOnRails/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :bigint(8)        not null, primary key
#  title        :string           not null
#  description  :text             not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, :description, presence: true

  belongs_to :moderator,
    foreign_key: :moderator_id,
    class_name: :User

  has_many :post_subs
  has_many :posts, through: :post_subs
end

RedditOnRails/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_moderator, only: [:edit]

  def new
    render :new
  end

  def index
    render :index
  end

  def create
    sub = Sub.new(sub_params)
    sub.moderator_id = current_user.id

    if sub.save
      redirect_to sub_url(sub)
    else
      flash[:errors] = sub.errors.full_messages
      redirect_to new_sub_url
    end
  end


  def show
    @sub = Sub.find(params[:id])

    if @sub
      render :show
    else
      redirect_to subs_url
    end
  end

  def edit
    render :edit
  end

  def update
    sub = Sub.find(params[:id])

    if sub.update(sub_params)
      redirect_to sub_url(sub)
    else
      flash[:errors] = sub.errors.full_messages
      redirect_to edit_sub_url
    end
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end

  def require_moderator
    @sub = Sub.find(params[:id])

    if @sub.moderator_id != current_user.id
      flash[:errors] = ["You're not authorized to modify this Sub!"]
      redirect_to sub_url(@sub)
    end
  end

end

RedditOnRails/app/helpers/sub_helper.rb
module SubHelper
end

RedditOnRails/app/views/subs/edit.html.erb
<h3>Edit Sub</h3>

<form class="" action="<%= sub_url(@sub) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="patch">

  <label>
    Title
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>

  <label>
    Description
    <input type="text" name="sub[description]" value="<%= @sub.description %>">
  </label>

  <input type="submit" name="" value="Edit Sub">
</form>

RedditOnRails/app/views/subs/index.html.erb
<h2>All the Subs</h2>

<ul>
  <% Sub.all.each do |sub| %>
    <li>
      <a href="<%= sub_url(sub) %>"><%= sub.title %></a>
      <p>Created by <%= sub.moderator.username %></p>
    </li>
  <% end %>
</ul>

<a href="<%= new_sub_url %>">Create New Sub</a>

RedditOnRails/app/views/subs/new.html.erb
<h3>New Sub</h3>

<form class="" action="<%= subs_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>
    Title
    <input type="text" name="sub[title]" value="">
  </label>

  <label>
    Description
    <input type="text" name="sub[description]" value="">
  </label>

  <input type="submit" name="" value="New Sub">
</form>

RedditOnRails/app/views/subs/show.html.erb
<h3><%= @sub.title %></h3>
<ul>
  <li><strong>Moderated by:</strong> <%= @sub.moderator.username %></li>
  <br>
  <li><strong>Description:</strong> <%= @sub.description %></li>
</ul>

<h4>Posts</h4>
<ul>
  <% @sub.posts.each do |post| %>
    <li>
      <a href="<%= post_url(post) %>"><%= post.title %></a>
      <br>
      Authored by: <i><%= post.author.username %></i>
    </li>
  <% end %>
</ul>

<a href="<%= edit_sub_url(@sub) %>">Edit Sub</a>
<br/>
<a href="<%= subs_url %>">Back to All Subs</a>

<a href="<%= new_sub_post_url(@sub) %>">Create New Post</a>